# Generated by Django 3.2.14 on 2022-09-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='active',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.AddField(
            model_name='movie',
            name='Directorname',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='website',
            field=models.URLField(default=0, max_length=100),
        ),
    ]
