# Generated by Django 3.2.14 on 2022-09-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_auto_20220907_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Directorname',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='website',
        ),
        migrations.AddField(
            model_name='movie',
            name='Description',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='movie',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
